// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PositiveNews.Infrastructure.Persistence;

#nullable disable

namespace PositiveNews.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleContent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentClean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryShort")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("ArticlesContent", "Catalog");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleMetadata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("und");

                    b.Property<long?>("ModeratedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PositivityScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Global");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("ModeratedBy");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("IX_ArticlesMeta_SourceId");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticlesMeta_Source_ExternalId")
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.HasIndex("LanguageCode", "RegionCode", "PublishedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_ArticlesMeta_Feed_Date")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ArticlesMetadata", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Articles_Positivity", "[PositivityScore] BETWEEN 0.0000 AND 1.0000");
                        });
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleTopic", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TopicId");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("IX_ArticleTopics_Topic_Lookup");

                    b.ToTable("ArticleTopics", "Catalog");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChangedField")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ModeratorId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_AuditLogs_Entity_History");

                    b.ToTable("AuditLogs", "Admin", t =>
                        {
                            t.HasCheckConstraint("CK_Audit_Entity", "[EntityType] IN ('Article', 'Comment', 'User', 'Source')");
                        });
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long?>("ModeratedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ModeratedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.HasIndex("ArticleId", "CreatedAt")
                        .HasDatabaseName("IX_Comments_Article_Thread")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("Comments", "Community");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.IngestionRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemsFetched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("IngestionRuns", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Ingestion_Status", "[Status] IN ('Running', 'Success', 'Failed', 'Partial')");
                        });
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "Identity");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiEncryptedKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("en");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeedUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ModeratedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("TrustScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.0m);

                    b.HasKey("Id");

                    b.HasIndex("ModeratedBy");

                    b.ToTable("Sources", "Catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Sources_Trust", "[TrustScore] >= 0.00");
                        });
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Topics", "Catalog");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarPictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModeratedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ModeratedBy");

                    b.ToTable("Users", "Identity");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserFeedPreference", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("MinPositivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0.5m);

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SortBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Date");

                    b.HasKey("UserId");

                    b.ToTable("UserFeedPreferences", "Identity", t =>
                        {
                            t.HasCheckConstraint("CK_UserPrefs_MinPositivity", "[MinPositivity] BETWEEN 0.00 AND 1.00");
                        });
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "Identity");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserSourceFilter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("UserSourceFilters", "Identity");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserTopicFilter", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("UserTopicFilters", "Identity");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleContent", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.ArticleMetadata", "Metadata")
                        .WithOne("Content")
                        .HasForeignKey("PositiveNews.Domain.Entities.ArticleContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleMetadata", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PositiveNews.Domain.Entities.Source", "Source")
                        .WithMany("Articles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moderator");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleTopic", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.ArticleMetadata", "Article")
                        .WithMany("ArticleTopics")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositiveNews.Domain.Entities.Topic", "Topic")
                        .WithMany("ArticleTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Comment", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.ArticleMetadata", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositiveNews.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PositiveNews.Domain.Entities.Comment", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PositiveNews.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Moderator");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.IngestionRun", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.Source", "Source")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Source", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.User", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.User", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserFeedPreference", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.User", "User")
                        .WithOne("FeedPreference")
                        .HasForeignKey("PositiveNews.Domain.Entities.UserFeedPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositiveNews.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserSourceFilter", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.Source", "Source")
                        .WithMany("UserSourceFilters")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositiveNews.Domain.Entities.User", "User")
                        .WithMany("SourceFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.UserTopicFilter", b =>
                {
                    b.HasOne("PositiveNews.Domain.Entities.Topic", "Topic")
                        .WithMany("UserTopicFilters")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PositiveNews.Domain.Entities.User", "User")
                        .WithMany("TopicFilters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.ArticleMetadata", b =>
                {
                    b.Navigation("ArticleTopics");

                    b.Navigation("Comments");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Source", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("IngestionRuns");

                    b.Navigation("UserSourceFilters");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.Topic", b =>
                {
                    b.Navigation("ArticleTopics");

                    b.Navigation("UserTopicFilters");
                });

            modelBuilder.Entity("PositiveNews.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FeedPreference");

                    b.Navigation("SourceFilters");

                    b.Navigation("TopicFilters");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
